export enum location {
  Argentina = 'Argentina',
  Brazil = 'Brazil',
  Canada = 'Canada',
  Chile = 'Chile',
  England = 'England',
  France = 'France',
  Germany = 'Germany',
  Italy = 'Italy',
  Japan = 'Japan',
  South_Korea = 'South_Korea',
  Mexico = 'Mexico',
  Qatar = 'Qatar',
  Russia = 'Russia',
  South_Africa = 'South_Africa',
  Spain = 'Spain',
  Sweden = 'Sweden',
  Switzerland = 'Switzerland',
  United_States = 'United_States',
  Uruguay = 'Uruguay',
  unknown = 'unknown',
}

export enum status {
  injured = 'injured',
  active = 'active',
  inactive = 'inactive',
  suspended = 'suspended',
  unknown = 'unknown',
}
